"""catalog

Revision ID: 0001
Revises:
Create Date: 2026-10-05 22:26:17.953210
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_colors",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("hex_value", sa.String(length=7), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_colors")),
        sa.UniqueConstraint("name", name=op.f("uq_body_colors_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_body_colors_slug")),
    )
    op.create_table(
        "control_types",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_types")),
        sa.UniqueConstraint("name", name=op.f("uq_control_types_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_control_types_slug")),
    )
    op.create_table(
        "panel_colors",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_panel_colors")),
        sa.UniqueConstraint("name", name=op.f("uq_panel_colors_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_panel_colors_slug")),
    )
    op.create_table(
        "products",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("model_code", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("max_temperature", sa.Integer(), nullable=False),
        sa.Column("heater_type", sa.String(length=120), nullable=False),
        sa.Column("warranty_months", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("model_code", name=op.f("uq_products_model_code")),
    )
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=120), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("body_color_id", sa.Uuid(), nullable=False),
        sa.Column("control_type_id", sa.Uuid(), nullable=False),
        sa.Column("panel_color_id", sa.Uuid(), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="RUB", nullable=False),
        sa.Column(
            "availability_status",
            sa.Enum(
                "in_stock", "made_to_order", "out_of_stock", "hidden", name="availability_status"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3", name=op.f("ck_product_variants_currency_length")
        ),
        sa.CheckConstraint("height_mm > 0", name=op.f("ck_product_variants_positive_height")),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_product_variants_non_negative_price")),
        sa.CheckConstraint("width_mm > 0", name=op.f("ck_product_variants_positive_width")),
        sa.ForeignKeyConstraint(
            ["body_color_id"],
            ["body_colors.id"],
            name=op.f("fk_product_variants_body_color_id_body_colors"),
        ),
        sa.ForeignKeyConstraint(
            ["control_type_id"],
            ["control_types.id"],
            name=op.f("fk_product_variants_control_type_id_control_types"),
        ),
        sa.ForeignKeyConstraint(
            ["panel_color_id"],
            ["panel_colors.id"],
            name=op.f("fk_product_variants_panel_color_id_panel_colors"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint(
            "product_id",
            "width_mm",
            "height_mm",
            "body_color_id",
            "control_type_id",
            "panel_color_id",
            name="uq_product_variants_configuration",
        ),
    )
    op.create_index(op.f("ix_product_variants_sku"), "product_variants", ["sku"], unique=True)
    op.create_table(
        "product_media",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("body_color_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.String(length=120), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("alt_text", sa.String(length=300), server_default="", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_product_media_positive_size")),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_product_media_non_negative_sort_order")
        ),
        sa.ForeignKeyConstraint(
            ["body_color_id"],
            ["body_colors.id"],
            name=op.f("fk_product_media_body_color_id_body_colors"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_media_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_product_media_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_media")),
        sa.UniqueConstraint("bucket", "object_key", name="uq_product_media_object"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_media")
    op.drop_index(op.f("ix_product_variants_sku"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_table("products")
    op.drop_table("panel_colors")
    op.drop_table("control_types")
    op.drop_table("body_colors")
    sa.Enum(name="availability_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
